/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElColorPicker: (typeof import("element-plus/es"))["ElColorPicker"];
    ElIcon: (typeof import("element-plus/es"))["ElIcon"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    ElRate: (typeof import("element-plus/es"))["ElRate"];
    ElSwitch: (typeof import("element-plus/es"))["ElSwitch"];
    IEpEdit: (typeof import("~icons/ep/edit"))["default"];
    IEpPlus: (typeof import("~icons/ep/plus"))["default"];
  }
}
